train:
  num_epochs: 5
  accum_iter: 10
  base_lr: 1.0
  batch_size: 16
  distributed: False
  label_smoothing: 0.1

dataset:
  dataset_name: 'roszcz/maestro-v1-sustain'
  bins: "3 3 3"
  sequence_size: 128

device: "cpu"
warmup: 3000
log_frequency: 10
file_prefix: "to_vel"
model_path: "to_vel_final.pt"
run_name: midi-transformer-${now:%Y-%m-%d-%H-%M}
project: "midi-transformer"

model:
  n: 6
  d_model: 512
  d_ff: 2048
  h: 8
  dropout: 0.1
