run_name: ""
model_epoch: "final"

n_examples: 5
random_examples: False
device: "cpu"
dataset_split: "test"
dataset:
  dataset_class: BinsToVelocityDataset
  dataset_name: null
  bins: null
  sequence_size: null
  n_tgt_dstart_bins: null
tasks:
  val_epoch: True
  translation: False
