train:
  num_epochs: 5
  accum_iter: 10
  base_lr: 1.0
  batch_size: 16
  distributed: False
  label_smoothing: 0.1

dataset_name: 'roszcz/maestro-v1-sustain'
target: velocity
augmentation_probability: 0.2
augmentation_rep: 0
cache_dataset: True

dataset:
  sequence_len: 128
  sequence_step: 42

  quantization:
    duration: 3
    dstart: 3
    velocity: 3

device: "cuda:0"
warmup: 3000
log_frequency: 10
run_name: midi-transformer-${now:%Y-%m-%d-%H-%M}
project: "midi-transformer"

model:
  n: 6
  d_model: 512
  d_ff: 2048
  h: 8
  dropout: 0.1
